import type { AnalyzerContext, ScanResult, Section } from '../types';
import { detectProjectProfile } from './readme';

const PLATFORMS = ['Docker', 'Railway', 'Render', 'Vercel', 'AWS', 'Azure', 'DigitalOcean'] as const;

export function generateDeploymentGuide(ctx: AnalyzerContext): ScanResult {
  const p = detectProjectProfile(ctx);
  const sections: Section[] = [];
  const md: string[] = [];
  md.push(`# Deployment Guide · ${p.name}`);
  md.push('');
  md.push(`Project type detected: **${p.framework || p.language}** (${p.packageManager || 'unknown package manager'}).`);
  md.push('');

  const isFrontend = p.framework === 'Next.js' || p.framework === 'React' || p.framework === 'Vue';
  const isBackend = !isFrontend;

  md.push('## Prerequisites');
  md.push('');
  md.push(`- ${p.packageManager ? p.packageManager.charAt(0).toUpperCase() + p.packageManager.slice(1) : 'A package manager'} installed`);
  md.push('- A Git repository hosted on GitHub/GitLab/Bitbucket');
  md.push(p.hasDatabase ? '- A managed database instance (see below)' : '');
  md.push('');

  const dockerfile = [
    `# Dockerfile generated by DevMate AI`,
    `# Base: ${p.language}${isFrontend ? ' · Node' : ''}`,
    ``,
    isFrontend
      ? [
          `FROM node:20-alpine AS builder`,
          `WORKDIR /app`,
          `COPY package*.json ./`,
          `RUN npm ci`,
          `COPY . .`,
          `RUN npm run build`,
          ``,
          `FROM node:20-alpine`,
          `WORKDIR /app`,
          `COPY --from=builder /app/.next ./.next`,
          `COPY --from=builder /app/node_modules ./node_modules`,
          `COPY --from=builder /app/package.json ./package.json`,
          `EXPOSE 3000`,
          `CMD ["npm", "start"]`,
        ].join('\n')
      : [
          `FROM node:20-alpine`,
          `WORKDIR /app`,
          `COPY package*.json ./`,
          `RUN npm ci --omit=dev`,
          `COPY . .`,
          `EXPOSE ${p.language === 'Go' ? '8080' : '4000'}`,
          `CMD ["npm", "start"]`,
        ].join('\n'),
    ``,
  ].join('\n');

  const dockerSection: Section = {
    title: 'Docker',
    content: ['```dockerfile', dockerfile, '```', '', '```bash', 'docker build -t ' + p.name + ' .', 'docker run -p 3000:3000 ' + p.name, '```'].join('\n'),
  };
  sections.push(dockerSection);
  md.push('## Docker');
  md.push('');
  md.push('```dockerfile');
  md.push(dockerfile);
  md.push('```');
  md.push('');

  if (isBackend) {
    const railway: Section = {
      title: 'Railway',
      content: ['1. Push this repository to GitHub.', '2. Create a new project at [railway.app](https://railway.app) and choose **Deploy from GitHub repo**.', '3. Set environment variables (see below).', '4. Add a Postgres plugin if the app uses a database.', '5. Deploy — Railway builds the Dockerfile automatically.'].join('\n'),
    };
    sections.push(railway);
    md.push('## Railway');
    md.push('');
    md.push(railway.content);
    md.push('');
  }

  if (isBackend) {
    const render: Section = {
      title: 'Render',
      content: ['1. From [render.com](https://render.com), create a **Web Service**.', '2. Point it at the GitHub repository.', '3. Build command: `npm ci && npm run build`', '4. Start command: `npm start`', '5. Add environment variables and a managed PostgreSQL instance.'].join('\n'),
    };
    sections.push(render);
    md.push('## Render');
    md.push('');
    md.push(render.content);
    md.push('');
  }

  if (isFrontend) {
    const vercel: Section = {
      title: 'Vercel',
      content: ['1. Install the Vercel CLI: `npm i -g vercel`', '2. Run `vercel` in the project root and log in.', '3. Link the project: `vercel link`.', '4. Configure environment variables in the Vercel dashboard.', '5. Deploy: `vercel --prod`.', '6. Enable automatic deploys from the Git integration for CI/CD.'].join('\n'),
    };
    sections.push(vercel);
    md.push('## Vercel');
    md.push('');
    md.push(vercel.content);
    md.push('');
  }

  const aws: Section = {
    title: 'AWS',
    content: isBackend
      ? ['**Option A — ECS/Fargate:** push the Docker image to ECR and create a Fargate task (REST API on port 4000).', '**Option B — Lambda:** use the serverless framework with an API Gateway proxy to the NestJS entry point.', 'Set secrets in Secrets Manager or SSM Parameter Store. Use RDS for Postgres and ElastiCache for Redis.'].join('\n')
      : ['**Option A — S3 + CloudFront:** run `npm run build` and sync the output directory to S3; add a CloudFront distribution for CDN + TLS.', '**Option B — Amplify:** connect the GitHub repo and let Amplify build/deploy automatically.'].join('\n'),
  };
  sections.push(aws);
  md.push('## AWS');
  md.push('');
  md.push(aws.content);
  md.push('');

  const azure: Section = {
    title: 'Azure',
    content: isBackend
      ? ['Use **Azure App Service** (Linux) with the Dockerfile, or **Container Apps** for a Fargate-like experience.', 'Set app settings as environment variables. Use Azure Database for PostgreSQL.'].join('\n')
      : ['Deploy the static build to **Azure Static Web Apps**, which supports Next.js and auto-configures CI from GitHub.'].join('\n'),
  };
  sections.push(azure);
  md.push('## Azure');
  md.push('');
  md.push(azure.content);
  md.push('');

  const digitalOcean: Section = {
    title: 'DigitalOcean',
    content: isBackend
      ? ['Use **DigitalOcean App Platform** connected to GitHub, or **Droplets** with the Docker image.', 'Add a managed Postgres (Supabase-compatible) database.'].join('\n')
      : ['Use **DigitalOcean App Platform (Static Site)** pointing at the build output directory.'].join('\n'),
  };
  sections.push(digitalOcean);
  md.push('## DigitalOcean');
  md.push('');
  md.push(digitalOcean.content);
  md.push('');

  md.push('## Environment Variables');
  md.push('');
  md.push('| Variable | Description |');
  md.push('| -------- | ----------- |');
  md.push('| `PORT` | HTTP port the server listens on |');
  md.push('| `DATABASE_URL` | Connection string for the database |');
  md.push('| `JWT_SECRET` | Signing secret for authentication tokens |');
  md.push(p.hasDatabase ? '| `REDIS_URL` | Cache / queue URL (if using Redis) |' : '');
  md.push('');

  return {
    summary: `Generated deployment instructions for ${PLATFORMS.length} platforms (detected ${p.framework || p.language}).`,
    markdown: md.join('\n'),
    sections,
    data: {
      profile: p,
      platformCount: PLATFORMS.length,
      dockerfile,
    },
  };
}
