import type { AnalyzerContext, ScanResult, Section } from '../types';
import { parseFunctions, isCodeFile, isTestFile } from '../utils';
import { detectProjectProfile } from './readme';

export function generateDocumentation(ctx: AnalyzerContext): ScanResult {
  const sections: Section[] = [];
  const stats = {
    filesAnalyzed: 0,
    functions: 0,
    classes: 0,
    endpoints: 0,
    tables: 0,
  };

  const md: string[] = [];
  md.push(`# ${ctx.repoName || 'Project'} Documentation`);
  md.push('');
  md.push('> Auto-generated by DevMate AI. Review before publishing.');
  md.push('');

  // --- Architecture overview ---
  md.push('## Architecture Overview');
  md.push('');
  const files = ctx.files.filter((f) => isCodeFile(f.path) && !isTestFile(f.path));
  const codeFiles = files.map((f) => f.path);
  md.push('### Folder structure');
  md.push('');
  md.push('```text');
  md.push(buildTree(codeFiles));
  md.push('```');
  md.push('');
  const deps = buildDependencyGraph(files);
  stats.filesAnalyzed = files.length;
  sections.push({ title: 'Architecture Overview', content: deps.mermaid });

  // --- Functions & classes ---
  md.push('## Functions & Classes');
  md.push('');
  const table: string[] = [];
  table.push('| Symbol | Type | File | Line | Params | Returns |');
  table.push('| ------ | ---- | ---- | ---- | ------ | ------- |');
  for (const file of files) {
    const parsed = parseFunctions(file.content, file.language);
    for (const p of parsed) {
      if (p.isClass) stats.classes += 1;
      else stats.functions += 1;
      table.push(
        `| \`${p.name}\` | ${p.isClass ? 'class' : 'function'} | \`${file.path}\` | ${p.line} | ${p.params.join(', ') || '—'} | ${p.returns || '—'} |`,
      );
    }
  }
  md.push(table.join('\n'));
  md.push('');
  sections.push({ title: 'Functions & Classes', content: table.join('\n') });

  // --- API endpoints ---
  md.push('## API Endpoints');
  md.push('');
  const endpoints = detectEndpoints(files);
  stats.endpoints = endpoints.length;
  if (endpoints.length === 0) {
    md.push('_No API endpoints detected._');
    md.push('');
  } else {
    const et = ['| Method | Route | File |', '| ------ | ----- | ---- |'];
    for (const e of endpoints) et.push(`| \`${e.method}\` | \`${e.route}\` | \`${e.file}\` |`);
    md.push(et.join('\n'));
    md.push('');
    sections.push({ title: 'API Endpoints', content: et.join('\n') });
  }

  // --- Database documentation ---
  md.push('## Database Schema');
  md.push('');
  const dbTables = detectDatabase(ctx);
  stats.tables = dbTables.length;
  if (dbTables.length === 0) {
    md.push('_No database schema detected. Check for `schema.prisma` or SQL migrations._');
    md.push('');
  } else {
    for (const t of dbTables) {
      md.push(`### \`${t.name}\``);
      md.push('');
      md.push('| Column | Type | Key |');
      md.push('| ------ | ---- | --- |');
      for (const c of t.columns) md.push(`| \`${c.name}\` | \`${c.type}\` | ${c.key} |`);
      md.push('');
    }
    sections.push({ title: 'Database Schema', content: dbTables.map((t) => `**${t.name}**: ${t.columns.map((c) => `${c.name} ${c.type}`).join(', ')}`).join('\n\n') });
  }

  // --- Generated markdown sections ---
  md.push('## Overview');
  md.push('');
  const profile = detectProjectProfile(ctx);
  md.push(`**${profile.language}**${profile.framework ? ` · ${profile.framework}` : ''} project with ${stats.filesAnalyzed} source files, ${stats.functions} functions and ${stats.classes} classes.`);
  md.push('');

  const markdown = md.join('\n');
  sections.unshift({ title: 'Overview', content: `**${profile.language}** project · ${stats.filesAnalyzed} files · ${stats.functions} functions · ${stats.classes} classes` });

  return {
    summary: `Documentation generated across ${stats.filesAnalyzed} files (${stats.functions} functions, ${stats.classes} classes, ${stats.endpoints} endpoints).`,
    markdown,
    sections,
    data: stats,
  };
}

function buildTree(paths: string[]): string {
  const root: Record<string, any> = {};
  for (const p of paths) {
    const parts = p.split('/');
    let node = root;
    for (const part of parts) {
      node = node[part] ??= {};
    }
  }
  const render = (node: Record<string, any>, prefix: string, out: string[]): void => {
    const keys = Object.keys(node);
    keys.forEach((k, i) => {
      const last = i === keys.length - 1;
      const children = Object.keys(node[k]).length > 0;
      out.push(`${prefix}${last ? '└── ' : '├── '}${k}${children ? '/' : ''}`);
      if (children) render(node[k], prefix + (last ? '    ' : '│   '), out);
    });
  };
  const out: string[] = [];
  for (const k of Object.keys(root)) out.push(k + (Object.keys(root[k]).length ? '/' : ''));
  const top = root[Object.keys(root)[0]];
  if (Object.keys(root).length === 1 && top && Object.keys(top).length) {
    render(root, '', out);
  }
  return out.join('\n');
}

function detectEndpoints(files: Array<{ path: string; content: string; language: string }>): Array<{ method: string; route: string; file: string }> {
  const out: Array<{ method: string; route: string; file: string }> = [];
  const methods = ['get', 'post', 'put', 'patch', 'delete'];
  for (const file of files) {
    const lines = file.content.replace(/\r\n/g, '\n').split('\n');
    for (let i = 0; i < lines.length; i++) {
      const t = lines[i].trim();
      for (const m of methods) {
        const re = new RegExp(`(@\\s*${m}\\s*\\(([^)]*)\\))|(\\.${m}\\s*\\(\\s*['"]([^'"]+)['"])`, 'i');
        const match = t.match(re);
        if (match) {
          const route = (match[2] || match[4] || '').replace(/['"]/g, '').replace(/`/g, '');
          out.push({ method: m.toUpperCase(), route, file: file.path });
        }
      }
    }
  }
  return out;
}

function buildDependencyGraph(files: Array<{ path: string; content: string; language: string }>): { mermaid: string; nodes: string[]; edges: string[] } {
  const nodeMap = new Map<string, string>();
  const edges: string[] = [];
  for (const file of files) {
    const id = file.path.replace(/[^a-zA-Z0-9_]/g, '_').slice(-40);
    nodeMap.set(file.path, id);
  }
  for (const file of files) {
    const imports = new Set<string>();
    if (['javascript', 'typescript'].includes(file.language)) {
      for (const m of file.content.matchAll(/(?:from\s+['"]|require\s*\(\s*['"])([./][^'"]+)/g)) imports.add(m[1]);
    }
    for (const imp of imports) {
      const target = resolveImport(file.path, imp, nodeMap);
      if (target && target !== file.path) {
        edges.push(`${nodeMap.get(file.path)} --> ${nodeMap.get(target)}`);
      }
    }
  }
  const mermaid = ['```mermaid', 'graph LR', ...edges.slice(0, 60), '```'].join('\n');
  return { mermaid, nodes: [...nodeMap.keys()], edges };
}

function resolveImport(from: string, imp: string, nodeMap: Map<string, string>): string | null {
  const base = from.split('/').slice(0, -1).join('/');
  const candidates = [imp];
  if (imp.startsWith('.')) {
    const resolved = joinPath(base, imp);
    candidates.push(resolved, resolved + '.ts', resolved + '.tsx', resolved + '.js', resolved + '.jsx', resolved + '/index.ts', resolved + '/index.js');
  }
  for (const c of candidates) {
    for (const key of nodeMap.keys()) {
      if (key === c) return key;
    }
  }
  for (const c of candidates) {
    for (const key of nodeMap.keys()) {
      if (key.endsWith(c)) return key;
    }
  }
  return null;
}

function joinPath(base: string, rel: string): string {
  const parts = base ? base.split('/') : [];
  for (const part of rel.split('/')) {
    if (part === '.') continue;
    if (part === '..') parts.pop();
    else parts.push(part);
  }
  return parts.join('/');
}

function detectDatabase(ctx: AnalyzerContext): Array<{ name: string; columns: Array<{ name: string; type: string; key: string }> }> {
  const out: Array<{ name: string; columns: Array<{ name: string; type: string; key: string }> }> = [];
  const schema = ctx.files.find((f) => f.path.toLowerCase().endsWith('schema.prisma'));
  if (schema) {
    const modelRe = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
    for (const m of schema.content.matchAll(modelRe)) {
      const name = m[1];
      const columns: Array<{ name: string; type: string; key: string }> = [];
      for (const cm of m[2].matchAll(/^\s*(\w+)\s+([A-Za-z]+)/gm)) {
        const col = cm[1];
        const type = cm[2];
        const key = col === 'id' ? 'PK' : /Id\b/.test(col) ? 'FK' : '';
        columns.push({ name: col, type, key });
      }
      out.push({ name, columns });
    }
  }
  if (out.length === 0) {
    const sql = ctx.files.find((f) => /\.(sql)$/.test(f.path));
    if (sql) {
      const createRe = /CREATE\s+TABLE\s+(?:"?(\w+)"?)\s*\(([\s\S]*?)\);/gi;
      for (const m of sql.content.matchAll(createRe)) {
        const columns: Array<{ name: string; type: string; key: string }> = [];
        for (const cm of m[2].matchAll(/^\s*"?(\w+)"?\s+([A-Z]+)/gim)) {
          const col = cm[1];
          const type = cm[2];
          columns.push({ name: col, type, key: col === 'id' ? 'PK' : '' });
        }
        out.push({ name: m[1], columns });
      }
    }
  }
  return out;
}
